children:
  spec:
    children:
      clusterIP:
        base: "This defines the IP address which the service will be exposed at. Putting none here makes it just run internally in the cluster."
      ports:
        base: "This defines the ports which this service will forward to the pods responsible."
      selector:
        base: "This defines the labels that should be used when selecting pods."
